export const STORE_ORIGIN:string;
export const STORE_HOSTS:Set<string>;
export const TAB_IDS:string[];
export const EXPECTED_IOS_BUNDLE_ID:string;
export const EXPECTED_ANDROID_PACKAGE:string;
export const DEFAULT_CITIES:string[];
export function safeStoreUrl(value:string):string|null;
export function safeImageUrl(value:string):string|null;
export function searchUrl(query:string):string;
export function normalisePreferences(input:unknown,knownIds:string[],cities?:string[]):{city:string;favourites:string[];reminderHour:number;reminderMinute:number;dismissedMessages:string[]};
export function filterProducts<T extends {id:string;title:string;subtitle:string;cuisine:string;diet:string;badge?:string;cities:string[];enabled?:boolean}>(products:T[],opts?:{query?:string;city?:string;diet?:string;savedOnly?:boolean;favourites?:string[]}):T[];
export function sortEnabled<T extends {enabled?:boolean;sortOrder?:number}>(items:T[]):T[];
export function activeMessages<T extends {enabled?:boolean;sortOrder?:number;startsAt?:string;endsAt?:string}>(items:T[],now?:number):T[];
export function parseTime(value:string):{hour:number;minute:number}|null;
export function formatTime(hour:number,minute:number):string;
export function reminderRequests(hour:number,minute:number):{identifier:string;content:{title:string;body:string;data:{tab:string;kind:string}};trigger:{weekday:number;hour:number;minute:number}}[];
export function safeNotificationTab(data:unknown):'home'|'explore'|'plan'|'orders'|'account';
export function contactUrl(action:{enabled?:boolean;channel:string;recipient?:string;subject?:string;body?:string},settings:{whatsappNumber?:string;supportEmail?:string}):string|null;
export function releaseErrors(env:Record<string,string|undefined>):string[];
